### ISSUE TITLE
Reload all frames when changing settings so you don't have the reload

### ISSUE THREAD

**Issue by filliph** [Justw8/TeleportMenu#17]
After upgrading to v6, I had to set a hearthstone via `/tpm [itemId]`. After doing so, pressing Esc did not show the hearthstone I set like I would expect.

**Comment by Justw8** [comment]
If you initially don't have a HS in your inventory, it doesn't load/setup the icon until a reload. this is 'working as intended' for now. I do plan to improve the frame generation so that a reload isn't required incase this situation happens, the same applies to learning / obtaining items and teleports. The list is only generated on reload/login and thus will not update inbetween.

**Comment by Justw8** [comment]
It now reloads frames when changing any setting in the latest alpha!
