### ISSUE TITLE
No hearthstones in options menu

### ISSUE THREAD

**Issue by angeroge** [Justw8/TeleportMenu#23]
I don't have Draenor and Dalaran hearthstone all the time in the options menu. I only have the normal hearthstone and also cannot see bonus hearthstones.

**Comment by Justw8** [comment]
Heya, what version is this with?

**Comment by angeroge** [comment]
Hello, yes. Sorry I forgot to mention the most important thing.
It's v7.

[image: image.png]

Behavior is the same on a laptop and also PC - WoW same version and Addon -
same version.

[image: image.png]


*George Andreascec*
*Phone: +40 761 676 921*




În mie., 28 aug. 2024 la 10:05, Justw8 ***@***.***> a scris:

**Comment by Justw8** [comment]
I'll still need some more information because we don't always show them under certain conditions.

1) do they show up after you reload? (/console reloadui)
2) Garrison and Dalaran HS require a quest to be done, if you havn't done those they won't show up.
3) The 'bonus hearthstones' are only 3 specific toys, if you don't have them they wont show.
4) The basic hearthstone only shows if you have it in your bags, or if you set a toy/random option.

**Comment by angeroge** [comment]
After a quick relog I got them back, I did not do anything else to the game
or the addon itself.

[image: image.png]

But to answer your questions:
1) They do show up now;
2) I completed quests for both draenor & dalaran way before I used this
addon;
3) The bonus ones are the deluxe/epic edition toys?
4) I am aware of this

*George Andreascec*
*Phone: +40 761 676 921*




În mie., 28 aug. 2024 la 18:01, Justw8 ***@***.***> a scris:

**Comment by Justw8** [comment]
Please try out `v7-8-gfbeb355`

**Comment by Justw8** [comment]
Closing for now, should be mostly fixed with v8. It things are still happening feel free to open a new ticket.
