### ISSUE TITLE
Missing teleports

### ISSUE THREAD

**Issue by animenerdfreddurst** [Justw8/TeleportMenu#5]
Not sure if I'm just a big dummy, but this doesn't have actual Hearthstone in it for me. Would also be super cool if it had Death Gate.

**Comment by Justw8** [comment]
Do you have a hs in your inventory? did you set a toy? (/tp list -> tp [itemId])

**Comment by animenerdfreddurst** [comment]
Okay, got the random Hearthstone working. Thank you.

Still think Death Gate would be a nice addition (and other potential class-based teleports, if they aren't in).

**Comment by Justw8** [comment]
I've added mage ports, I'll note the dk death gate to add as well!

**Comment by animenerdfreddurst** [comment]
Shamans also get Astral Recall, Druids get something to do with the Dreamglade, Monks get something as well. Can't think of any others off the top of my head.

**Comment by SJPadbury** [comment]
![image](https://github.com/user-attachments/assets/9965463d-cd46-4a54-afa5-63788b9d1efa)

I like the idea of having it on the menu rather than a button on the minimap like Tome of Teleportation. I'm actually surprised nobody else has put stuff on the menu like this.
I'd love to see Engineering wormholes, or other toys that teleport you places. 
I attached the screenshot with ToT open for comparison.

**Comment by Justw8** [comment]
Wormholes should already be available on there! (does require you to be able to use them.)

**Comment by Justw8** [comment]
closing this as I added wormholes, I will open a separate issue with all missing and planned teleports to keep it combined in 1 post.
